// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rewear.Data;

#nullable disable

namespace Rewear.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904023000_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rewear.Models.Categoria", b =>
                {
                    b.Property<decimal>("idCategoria")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Rewear.Models.EstadoPrenda", b =>
                {
                    b.Property<decimal>("idEstadoPrenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idEstadoPrenda");

                    b.ToTable("EstadosPrenda");
                });

            modelBuilder.Entity("Rewear.Models.Publicacion", b =>
                {
                    b.Property<decimal>("idPublicacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Categoria_idCategoria")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstadoPrenda_idEstadoPrenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendedor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPublicacion");

                    b.HasIndex("Categoria_idCategoria");

                    b.HasIndex("EstadoPrenda_idEstadoPrenda");

                    b.ToTable("Publicaciones");
                });

            modelBuilder.Entity("Rewear.Models.Publicacion", b =>
                {
                    b.HasOne("Rewear.Models.Categoria", "Categoria")
                        .WithMany("Publicaciones")
                        .HasForeignKey("Categoria_idCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rewear.Models.EstadoPrenda", "EstadoPrenda")
                        .WithMany("Publicaciones")
                        .HasForeignKey("EstadoPrenda_idEstadoPrenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("EstadoPrenda");
                });

            modelBuilder.Entity("Rewear.Models.Categoria", b =>
                {
                    b.Navigation("Publicaciones");
                });

            modelBuilder.Entity("Rewear.Models.EstadoPrenda", b =>
                {
                    b.Navigation("Publicaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
