// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rewear.Data;

#nullable disable

namespace Rewear.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rewear.Models.Categoria", b =>
                {
                    b.Property<decimal>("idCategoria")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCategoria");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            idCategoria = 1m,
                            Descripcion = "Ropa y prendas para mujer",
                            Nombre = "Mujer"
                        },
                        new
                        {
                            idCategoria = 2m,
                            Descripcion = "Ropa y prendas para hombre",
                            Nombre = "Hombre"
                        },
                        new
                        {
                            idCategoria = 3m,
                            Descripcion = "Calzado de segunda mano",
                            Nombre = "Zapatos"
                        },
                        new
                        {
                            idCategoria = 4m,
                            Descripcion = "Bolsos, carteras y otros accesorios",
                            Nombre = "Accesorios"
                        });
                });

            modelBuilder.Entity("Rewear.Models.EstadoPrenda", b =>
                {
                    b.Property<decimal>("idEstadoPrenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idEstadoPrenda");

                    b.ToTable("EstadosPrenda");

                    b.HasData(
                        new
                        {
                            idEstadoPrenda = 1m,
                            Descripcion = "Prenda sin uso",
                            Nombre = "Nuevo"
                        },
                        new
                        {
                            idEstadoPrenda = 2m,
                            Descripcion = "Prenda usada pocas veces",
                            Nombre = "Como nuevo"
                        },
                        new
                        {
                            idEstadoPrenda = 3m,
                            Descripcion = "Prenda usada pero bien conservada",
                            Nombre = "Buen estado"
                        },
                        new
                        {
                            idEstadoPrenda = 4m,
                            Descripcion = "Prenda con signos de uso",
                            Nombre = "Usado"
                        });
                });

            modelBuilder.Entity("Rewear.Models.Publicacion", b =>
                {
                    b.Property<decimal>("idPublicacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Categoria_idCategoria")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstadoPrenda_idEstadoPrenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendedor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPublicacion");

                    b.HasIndex("Categoria_idCategoria");

                    b.HasIndex("EstadoPrenda_idEstadoPrenda");

                    b.ToTable("Publicaciones");

                    b.HasData(
                        new
                        {
                            idPublicacion = 1m,
                            Categoria_idCategoria = 1m,
                            Descripcion = "Blazer en buen estado, talla M.",
                            EstadoPrenda_idEstadoPrenda = 3m,
                            Imagen = "/images/blazer.jpg",
                            Precio = 65.00m,
                            Titulo = "Blazer verde menta",
                            Vendedor = "María"
                        },
                        new
                        {
                            idPublicacion = 2m,
                            Categoria_idCategoria = 1m,
                            Descripcion = "Suéter tejido color beige, talla M.",
                            EstadoPrenda_idEstadoPrenda = 2m,
                            Imagen = "/images/sueter.jpg",
                            Precio = 45.00m,
                            Titulo = "Suéter tejido beige",
                            Vendedor = "Ana"
                        },
                        new
                        {
                            idPublicacion = 3m,
                            Categoria_idCategoria = 1m,
                            Descripcion = "Jeans azul de corte mom fit, talla 28.",
                            EstadoPrenda_idEstadoPrenda = 3m,
                            Imagen = "/images/jeans.jpg",
                            Precio = 55.00m,
                            Titulo = "Jeans mom fit",
                            Vendedor = "Carla"
                        },
                        new
                        {
                            idPublicacion = 4m,
                            Categoria_idCategoria = 3m,
                            Descripcion = "Zapatillas blancas en buen estado, talla 38.",
                            EstadoPrenda_idEstadoPrenda = 3m,
                            Imagen = "/images/zapatillas.jpg",
                            Precio = 80.00m,
                            Titulo = "Zapatillas blancas",
                            Vendedor = "Luis"
                        },
                        new
                        {
                            idPublicacion = 5m,
                            Categoria_idCategoria = 4m,
                            Descripcion = "Cartera marrón de segunda mano.",
                            EstadoPrenda_idEstadoPrenda = 2m,
                            Imagen = "/images/cartera.jpg",
                            Precio = 60.00m,
                            Titulo = "Cartera marrón",
                            Vendedor = "Sofía"
                        });
                });

            modelBuilder.Entity("Rewear.Models.Publicacion", b =>
                {
                    b.HasOne("Rewear.Models.Categoria", "Categoria")
                        .WithMany("Publicaciones")
                        .HasForeignKey("Categoria_idCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rewear.Models.EstadoPrenda", "EstadoPrenda")
                        .WithMany("Publicaciones")
                        .HasForeignKey("EstadoPrenda_idEstadoPrenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("EstadoPrenda");
                });

            modelBuilder.Entity("Rewear.Models.Categoria", b =>
                {
                    b.Navigation("Publicaciones");
                });

            modelBuilder.Entity("Rewear.Models.EstadoPrenda", b =>
                {
                    b.Navigation("Publicaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
